#!/bin/bash

#======================================================================================================================
# Title         : ssh_ip_allow.sh
# Description   : Initializes a mint Ubuntu 20.04 LTS installation
# Author        : Mark Dumay
# Date          : June 9th, 2020
# Version       : 0.1
# Usage         : sudo ./ssh_ip_allow.sh
# Repository    : 
# Comments      : Generated by ubuntu-secure.sh
#======================================================================================================================

#======================================================================================================================
# Constants
#======================================================================================================================
IP_SSH_ALLOW_HOSTNAME={IP_SSH_ALLOW_HOSTNAME}
IP_SSH_PORT={IP_SSH_PORT}


#======================================================================================================================
# Variables
#======================================================================================================================
NEW_IP=$(dig "$IP_SSH_ALLOW_HOSTNAME" +short | tail -n 1)
OLD_IP=$(/usr/sbin/ufw status | grep "$IP_SSH_ALLOW_HOSTNAME" | head -n1 | tr -s ' ' | cut -f3 -d ' ')


#======================================================================================================================
# Main Script
#======================================================================================================================
if [ "$NEW_IP" == "$OLD_IP" ] ; then
    echo IP address has not changed
else
    if [ -n "$OLD_IP" ] ; then
        /usr/sbin/ufw delete allow from "$OLD_IP" to any port "$IP_SSH_PORT"
    fi
    /usr/sbin/ufw allow from "$NEW_IP" to any port "$IP_SSH_PORT" comment "$IP_SSH_ALLOW_HOSTNAME"
    echo iptables have been updated
fi
