---
# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.
- name: Harden an Ubuntu server
  hosts: test
  user: admin
  gather_facts: no  # gathered by tasks/sshd.yml instead
  roles:
    - role: holms.fqdn
      tags: fqdn
      become: yes
    - role: konstruktoid.hardening

  vars:
    ansible_become_pass: "{{ users_enabled.admin.password }}"
    sshd_admin_net:
      - 10.0.0.0/24 # private IP subnet for Vagrant VM
    sshd_client_alive_count_max: 2
    sshd_port: 2222
    sshd_max_sessions: 2
    docker_swarm_multi_node: false
    ufw_outgoing_traffic:
      - 43                    # WHOIS
      - 53                    # DNS
      - 80                    # HTTP
      - 123                   # NTP
      - 443                   # HTTPS
      - 853                   # DNS over TLS
      - "{{ sshd_port }}"     # SSH (remapped)

  pre_tasks:
    # TODO: check this
    - name: Add Docker Swarm ports to ufw
      set_fact:
        ufw_outgoing_traffic: "{{ ufw_outgoing_traffic + ufw_docker_swarm_ports }}"
      when: docker_swarm_multi_node
      tags:
        - always

    - name: Configure SSH port and gather facts
      import_tasks: tasks/sshd.yml
      tags:
        - always

    - name: Whitelist public IP address of local machine for SSH
      import_tasks: tasks/ip.yml
      tags:
        - ufw
        - ssh
        - ip

  tasks:
    - name: Validate hostname and FQDN
      include_tasks: tasks/hostname.yml
      tags:
        - timezone

    - name: Validate timezone
      include_tasks: tasks/timezone.yml
      tags:
        - timezone
  
    - name: Validate authorized users
      include_tasks: tasks/users.yml
      tags:
        - users

  post_tasks:
    - name: Modify audit.rules
      include_tasks: tasks/audit.yml
      tags:
        - auditd
        - audit.rules
    
    - name: Configure DDNS access for SSH access via ufw
      include_tasks: tasks/ufw.yml
      tags:
        - ufw
        - ssh

  handlers:
    - import_tasks: handlers/main.yml
...